# Generated by Django 2.1.7 on 2019-03-20 01:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('cloud_provider', models.CharField(choices=[('Anchnet', '安畅云'), ('Aliyun', '阿里云'), ('AWS', 'AWS'), ('Qcloud', '腾讯云'), ('HuaWei', '华为云')], default='', max_length=50, verbose_name='Cloud Provider')),
                ('accesskey_id', models.CharField(max_length=200, verbose_name='AccessKey ID')),
                ('accesskey_secert', models.CharField(max_length=200, verbose_name='AccessKey Secert')),
                ('is_available', models.BooleanField(default=1, verbose_name='Is Available')),
                ('last_sync_time', models.DateTimeField(blank=True, null=True, verbose_name='Last sync time')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Cloud Accounts',
            },
        ),
    ]
