# Generated by Django 2.1.7 on 2019-04-25 03:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0025_auto_20190221_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='AK',
            fields=[
                ('org_id', models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='Organization')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cloud_name', models.CharField(choices=[('Ali', 'Ali'), ('Tencent', 'Tencent'), ('HuaWei', 'Tencent'), ('AWS', 'AWS')], default='Tencent', max_length=32, verbose_name='cloud_name')),
                ('secret_id', models.CharField(max_length=128, verbose_name='secret_id')),
                ('secret_key', models.CharField(max_length=128, verbose_name='secret_key')),
            ],
            options={
                'verbose_name': 'AK',
            },
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='auto_push',
            field=models.BooleanField(default=False, verbose_name='Auto push'),
        ),
    ]
